import SkywaveShared
import SwiftUI

/// A miniature of a skin's phone home screen for the skin picker and onboarding.
///
/// These are pre-rendered screenshots of the demo app (Resources/Thumbnails, generated by
/// Scripts/make_thumbnails.sh), one per skin and language. Rendering the skins live inside the
/// picker was tried first: ten complete interfaces with their own tab bars, navigation bars,
/// maps and timers leaked navigation state and gestures into the page around them and made
/// the picker heavy, so the picker only ever shows pictures now.
struct SkinThumbnail: View {
    let skin: SkinID

    var body: some View {
        Group {
            if let image = SkinThumbnailStore.image(for: skin) {
                image.resizable().aspectRatio(contentMode: .fill)
            } else {
                // Missing asset: a quiet placeholder in the skin's colors.
                ZStack {
                    SkinTheme.of(skin).background
                    Image(systemName: skin.symbol).font(.largeTitle).foregroundStyle(skin.accent)
                }
            }
        }
        .aspectRatio(390.0 / 844.0, contentMode: .fit)
        .clipped()
        .accessibilityHidden(true)
    }
}

@MainActor
enum SkinThumbnailStore {
    private static var cache: [String: Image] = [:]

    /// `en`, `zh-Hans` or `zh-Hant`, following the language the app is running in.
    static var language: String {
        let preferred = Bundle.module.preferredLocalizations.first ?? "en"
        if preferred.hasPrefix("zh-Hant") || preferred == "zh-TW" || preferred == "zh-HK" { return "zh-Hant" }
        if preferred.hasPrefix("zh") { return "zh-Hans" }
        return "en"
    }

    static func image(for skin: SkinID) -> Image? {
        let name = "thumb-\(skin.rawValue)-\(language)"
        if let cached = cache[name] { return cached }
        let url = [name, "thumb-\(skin.rawValue)-en"].lazy.compactMap { resource in
            Bundle.module.url(forResource: resource, withExtension: "jpg")
                ?? Bundle.module.url(forResource: resource, withExtension: "jpg", subdirectory: "Thumbnails")
        }.first
        guard let url else { return nil }
        #if os(macOS)
            guard let platformImage = NSImage(contentsOf: url) else { return nil }
            let image = Image(nsImage: platformImage)
        #else
            guard let platformImage = UIImage(contentsOfFile: url.path) else { return nil }
            let image = Image(uiImage: platformImage)
        #endif
        cache[name] = image
        return image
    }
}
